// Copyright (c) 2026 Ronnie Andrews, Jr. (Team Xcelerator Inc.®)
// All rights reserved. See LICENSE in the repository root.

//! Layer 2 — PARI/GP cross-check for the HP eigensolver.
//!
//! Loads `tests/fixtures/eigen_reference.json` (generated by
//! `tests/fixtures/generate_eigen_reference.gp` via PARI/GP at 2000-digit
//! precision) and verifies our HP eigensolver matches PARI's eigenvalues
//! to ≥500 decimal digits.
//!
//! This is the strongest independent-implementation check possible:
//! different language, different algorithms, different arithmetic backend.
//!
//! If `eigen_reference.json` is missing (i.e. user hasn't generated it
//! with PARI yet), this test is skipped with an informative message.

#![cfg(feature = "hp")]

use serde_json::Value;
use rug::Float;

use xc_numerics::eigen::dense_symmetric_eigenvalues_hp;
use xc_numerics::fmt::{display_hp, matching_digits};

/// Working precision for our HP solver. PARI generates at 2000 digits;
/// we run at 1000 and require ≥500 matching digits — more than enough
/// margin to expose any bugs.
const TEST_PRECISION_BITS: u32 = 3338;  // ≈ 1000 decimal digits
const MIN_MATCHING_DIGITS: f64 = 500.0;

fn fixture_path() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("fixtures");
    p.push("eigen_reference.json");
    p
}

/// Skip-if-missing wrapper. Returns `None` when the fixture isn't present
/// (so the test passes vacuously instead of failing on machines without PARI).
fn load_fixture() -> Option<Value> {
    let path = fixture_path();
    if !path.exists() {
        eprintln!(
            "[eigen_reference] fixture not found at {} — skipping. \
             Generate with: cd tests/fixtures && gp -q generate_eigen_reference.gp > eigen_reference.json",
            path.display()
        );
        return None;
    }
    let data = std::fs::read_to_string(&path).expect("read fixture");
    Some(serde_json::from_str(&data).expect("parse fixture JSON"))
}

#[test]
fn pari_cross_check_all_cases() {
    let fixture = match load_fixture() {
        Some(f) => f,
        None => return,
    };

    let cases = fixture["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "no test cases in fixture");

    let prec = TEST_PRECISION_BITS;
    let min_digits = Float::with_val(prec, MIN_MATCHING_DIGITS);

    let mut total_cases = 0;
    let mut total_eigenvalues_checked = 0;

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let n = case["n"].as_u64().expect("case n") as usize;
        let mat_strs: Vec<&str> = case["matrix"].as_array().expect("matrix")
            .iter()
            .map(|v| v.as_str().expect("matrix entry"))
            .collect();
        let eval_strs: Vec<&str> = case["eigenvalues_ascending"].as_array().expect("eigenvalues")
            .iter()
            .map(|v| v.as_str().expect("eigenvalue"))
            .collect();

        assert_eq!(mat_strs.len(), n * n, "case {} matrix length mismatch", name);
        assert_eq!(eval_strs.len(), n, "case {} eigenvalue count mismatch", name);

        // Parse matrix into HP at our test precision.
        // PARI's printf %Pe inserts whitespace before the exponent (e.g.
        // "2.0...0 e0"); strip whitespace before parsing so rug accepts it.
        let matrix: Vec<Float> = mat_strs.iter()
            .map(|s| {
                let cleaned: String = s.chars().filter(|c| !c.is_whitespace()).collect();
                Float::with_val(prec, Float::parse(&cleaned).expect("parse matrix entry"))
            })
            .collect();

        // Reference eigenvalues at our test precision.
        let reference: Vec<Float> = eval_strs.iter()
            .map(|s| {
                let cleaned: String = s.chars().filter(|c| !c.is_whitespace()).collect();
                Float::with_val(prec, Float::parse(&cleaned).expect("parse eigenvalue"))
            })
            .collect();

        // Run our solver.
        let computed = dense_symmetric_eigenvalues_hp(&matrix, n, prec)
            .unwrap_or_else(|e| panic!("case {}: solver failed: {}", name, e));
        assert_eq!(computed.len(), n,
            "case {}: solver returned {} eigenvalues, expected {}",
            name, computed.len(), n);

        // Verify each computed eigenvalue matches the reference to
        // ≥MIN_MATCHING_DIGITS decimal digits.
        for (k, (c, r)) in computed.iter().zip(reference.iter()).enumerate() {
            let m = matching_digits(c, r);
            if !m.is_infinite() && m < min_digits {
                panic!(
                    "case '{}' eigenvalue {} matches PARI reference to only {} digits \
                     (need ≥{}). computed={}, reference={}",
                    name, k,
                    display_hp(&m, 4),
                    MIN_MATCHING_DIGITS,
                    display_hp(c, 8),
                    display_hp(r, 8)
                );
            }
            total_eigenvalues_checked += 1;
        }

        eprintln!("[eigen_reference] case '{}' (n={}): all {} eigenvalues match PARI to ≥{} digits",
            name, n, n, MIN_MATCHING_DIGITS as u32);
        total_cases += 1;
    }

    eprintln!("[eigen_reference] verified {} cases, {} total eigenvalues",
        total_cases, total_eigenvalues_checked);
}
