// Copyright (c) 2026 Ronnie Andrews, Jr. (Team Xcelerator Inc.®)
// All rights reserved. See LICENSE in the repository root.

//! Layer 2 — PARI/GP cross-check for `tridiag_eigenvalues_hp`.
//!
//! Loads `tests/fixtures/tridiag_eigen_reference.json` (generated by
//! `tests/fixtures/generate_tridiag_eigen_reference.gp` via PARI/GP at
//! 2000-digit precision) and verifies the tridiagonal QR solver
//! matches PARI's eigenvalues to ≥500 decimal digits, on a variety of
//! structured and random tridiagonals.
//!
//! Why this is independent from the existing `eigen_reference.rs` test:
//! that test exercises `dense_symmetric_eigenvalues_hp`, which composes
//! Householder tridiagonalization with the tridiagonal QR. A bug
//! confined to the tridiagonal-only path would be masked there by
//! Householder's structure (random matrices it produces don't expose
//! the QR's deflation path the way Wilkinson + diagonal-only inputs do).
//! Cross-checking `tridiag_eigenvalues_hp` directly against PARI on
//! tridiagonal-shaped inputs provides independent coverage.
//!
//! If `tridiag_eigen_reference.json` is missing (i.e. user hasn't
//! generated it with PARI yet), this test is skipped with an
//! informative message — same pattern as `eigen_reference.rs`.

#![cfg(feature = "hp")]

use serde_json::Value;
use rug::Float;

use xc_numerics::eigen::tridiag_eigenvalues_hp;
use xc_numerics::fmt::{display_hp, matching_digits};

const TEST_PRECISION_BITS: u32 = 3338;  // ≈ 1000 decimal digits
const MIN_MATCHING_DIGITS: f64 = 500.0;

fn fixture_path() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("tests");
    p.push("fixtures");
    p.push("tridiag_eigen_reference.json");
    p
}

fn load_fixture() -> Option<Value> {
    let path = fixture_path();
    if !path.exists() {
        eprintln!(
            "[tridiag_eigen_reference] fixture not found at {} — skipping. \
             Generate with: cd tests/fixtures && gp -q generate_tridiag_eigen_reference.gp > tridiag_eigen_reference.json",
            path.display()
        );
        return None;
    }
    let data = std::fs::read_to_string(&path).expect("read fixture");
    Some(serde_json::from_str(&data).expect("parse fixture JSON"))
}

#[test]
fn pari_cross_check_tridiag_all_cases() {
    let fixture = match load_fixture() {
        Some(f) => f,
        None => return,
    };

    let cases = fixture["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "no test cases in fixture");

    let prec = TEST_PRECISION_BITS;
    let min_digits = Float::with_val(prec, MIN_MATCHING_DIGITS);

    let mut total_cases = 0;
    let mut total_eigenvalues_checked = 0;

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let n = case["n"].as_u64().expect("case n") as usize;

        let diag_strs: Vec<&str> = case["diag"].as_array().expect("diag")
            .iter().map(|v| v.as_str().expect("diag entry")).collect();
        let off_strs: Vec<&str> = case["off_diag"].as_array().expect("off_diag")
            .iter().map(|v| v.as_str().expect("off_diag entry")).collect();
        let eval_strs: Vec<&str> = case["eigenvalues_ascending"].as_array()
            .expect("eigenvalues_ascending")
            .iter().map(|v| v.as_str().expect("eigenvalue")).collect();

        assert_eq!(diag_strs.len(), n, "case {} diag length mismatch", name);
        assert_eq!(off_strs.len(), n.saturating_sub(1),
            "case {} off_diag length mismatch", name);
        assert_eq!(eval_strs.len(), n,
            "case {} eigenvalue count mismatch", name);

        // Parse diag, off_diag, and reference eigenvalues into HP.
        // PARI's printf %Pe inserts whitespace before the exponent, e.g.
        // "2.0...0 e0"; strip it before parsing so rug accepts the input.
        let parse_hp = |s: &str| -> Float {
            let cleaned: String = s.chars().filter(|c| !c.is_whitespace()).collect();
            Float::with_val(prec, Float::parse(&cleaned).expect("parse"))
        };

        let diag: Vec<Float> = diag_strs.iter().map(|s| parse_hp(s)).collect();
        let off_diag: Vec<Float> = off_strs.iter().map(|s| parse_hp(s)).collect();
        let reference: Vec<Float> = eval_strs.iter().map(|s| parse_hp(s)).collect();

        // Run the tridiagonal QR.
        let computed = tridiag_eigenvalues_hp(&diag, &off_diag, prec)
            .unwrap_or_else(|e| panic!("case {}: tridiag_eigenvalues_hp failed: {}", name, e));
        assert_eq!(computed.len(), n,
            "case {}: solver returned {} eigenvalues, expected {}",
            name, computed.len(), n);

        // Both `computed` and `reference` are sorted ascending. Compare
        // element-wise.
        for (k, (c, r)) in computed.iter().zip(reference.iter()).enumerate() {
            let m = matching_digits(c, r);
            if !m.is_infinite() && m < min_digits {
                panic!(
                    "case '{}' eigenvalue {} matches PARI reference to only {} digits \
                     (need ≥{}). computed={}, reference={}",
                    name, k,
                    display_hp(&m, 4),
                    MIN_MATCHING_DIGITS,
                    display_hp(c, 8),
                    display_hp(r, 8)
                );
            }
            total_eigenvalues_checked += 1;
        }

        eprintln!(
            "[tridiag_eigen_reference] case '{}' (n={}): all {} eigenvalues match PARI to ≥{} digits",
            name, n, n, MIN_MATCHING_DIGITS as u32
        );
        total_cases += 1;
    }

    eprintln!(
        "[tridiag_eigen_reference] verified {} cases, {} total eigenvalues",
        total_cases, total_eigenvalues_checked
    );
}
