/*
 * generate_eigen_reference.gp — PARI/GP script generating ground-truth
 * symmetric eigenvalue test data at 2000-digit precision.
 *
 * Output: prints JSON to stdout. Redirect to fixtures/eigen_reference.json.
 *
 * Usage:
 *   gp -q generate_eigen_reference.gp > eigen_reference.json
 */

\\ Set 2000 decimal digit precision.
default(realprecision, 2000);

\\ Format a real number to its full-precision decimal string in
\\ scientific notation (e.g. "1.234567890e-50"). PARI's printf with
\\ "%.NPe" prints N digits after the decimal point in scientific form.
\\ We use realprecision-1 digits after the decimal so total significant
\\ digits = realprecision. The result is parseable by `Float::parse` in rug.
fmt_real(x) = Strprintf("%.*Pe", default(realprecision) - 1, x * 1.0);

\\ Build a Strang's tridiagonal n×n: diag=2, off=-1.
strang(n) = matrix(n, n, i, j, if(i == j, 2, if(abs(i - j) == 1, -1, 0)));

\\ Build a Hilbert n×n.
hilb(n) = matrix(n, n, i, j, 1 / (i + j - 1));

\\ Build a Frank n×n: F[i,j] = min(i,j).
frank(n) = matrix(n, n, i, j, min(i, j));

\\ Build a Wilkinson W_{2k+1}: diag k..1,0,1..k; off=1.
wilkinson_w(half) = {
    my(n, M, d);
    n = 2 * half + 1;
    M = matrix(n, n, i, j, 0);
    for(i = 1, n,
        d = abs(i - half - 1);
        M[i, i] = d;
        if(i > 1, M[i, i-1] = 1);
        if(i < n, M[i, i+1] = 1);
    );
    M;
}

\\ Output one test case as a JSON object.
emit_case(name, M) = {
    my(n, evals, eval_strs, mat_strs, k, i, j);
    n = matsize(M)[1];

    \\ Eigenvalues via real-root finding on the characteristic polynomial.
    \\ For symmetric matrices, all eigenvalues are real.
    evals = polrootsreal(charpoly(M));
    evals = vecsort(evals);

    \\ Sanity: number of eigenvalues should equal n.
    if(#evals != n,
        error("eigenvalue count ", #evals, " != n=", n, " for case ", name));

    print("    {");
    print("      \"name\": \"", name, "\",");
    print("      \"n\": ", n, ",");

    \\ Matrix entries (flat row-major).
    print("      \"matrix\": [");
    for(i = 1, n,
        for(j = 1, n,
            my(s, sep);
            s = fmt_real(M[i, j] * 1.0);  \\ Force real type for fmt
            sep = if(i == n && j == n, "", ",");
            print("        \"", s, "\"", sep);
        );
    );
    print("      ],");

    \\ Eigenvalues, ascending.
    print("      \"eigenvalues_ascending\": [");
    for(k = 1, n,
        my(s, sep);
        s = fmt_real(evals[k]);
        sep = if(k == n, "", ",");
        print("        \"", s, "\"", sep);
    );
    print("      ]");

    print("    }");
}

\\ Helper: emit case with comma separator (all but last).
emit_case_comma(name, M) = {
    emit_case(name, M);
    print(",");
}

\\ Main output.
print("{");
print("  \"description\": \"HP eigensolver reference data generated by PARI/GP\",");
print("  \"realprecision\": ", default(realprecision), ",");
print("  \"cases\": [");

emit_case_comma("strang_n3", strang(3));
emit_case_comma("strang_n4", strang(4));
emit_case_comma("strang_n7", strang(7));
emit_case_comma("hilbert_n3", hilb(3));
emit_case_comma("hilbert_n5", hilb(5));
emit_case_comma("frank_n4", frank(4));
emit_case_comma("frank_n6", frank(6));
emit_case_comma("wilkinson_w7", wilkinson_w(3));
emit_case("wilkinson_w11", wilkinson_w(5));  \\ Last — no comma

print("  ]");
print("}");
quit;
