/*
 * generate_tridiag_eigen_reference.gp — PARI/GP script generating
 * ground-truth eigenvalues for symmetric tridiagonal matrices, used to
 * cross-check `xc-numerics::eigen::tridiag_eigenvalues_hp` directly
 * (without going through the dense Householder pipeline first).
 *
 * Output: prints JSON to stdout. Redirect to
 *   fixtures/tridiag_eigen_reference.json.
 *
 * Usage:
 *   gp -q generate_tridiag_eigen_reference.gp > tridiag_eigen_reference.json
 *
 * The companion test (xc-numerics/tests/tridiag_eigen_reference.rs)
 * loads each case at HP-1000 working precision and verifies
 * tridiag_eigenvalues_hp returns matching eigenvalues to >=500 decimal
 * digits. Skipped vacuously when the JSON file is absent.
 */

\\ 2000-digit reference precision (matches the existing dense-matrix
\\ fixture). PARI's polrootsreal computes all real roots of a polynomial
\\ to working precision, which here is the characteristic polynomial of
\\ the tridiagonal expressed as a full matrix.
default(realprecision, 2000);

\\ Format a real number to its full-precision decimal string in scientific
\\ notation, parseable by `rug::Float::parse`.
fmt_real(x) = Strprintf("%.*Pe", default(realprecision) - 1, x * 1.0);

\\ Build a tridiagonal n x n matrix from diag (length n) and off (length n-1).
\\ Symmetric: M[i,j] = diag[i] when i==j, off[min(i,j)] when |i-j|=1, else 0.
build_tridiag(diag_v, off_v) = {
    my(n, M);
    n = #diag_v;
    M = matrix(n, n, i, j, 0);
    for(i = 1, n,
        M[i, i] = diag_v[i];
        if(i > 1, M[i, i-1] = off_v[i-1]);
        if(i < n, M[i, i+1] = off_v[i]);
    );
    M;
}

\\ Strang's tridiagonal: diag = [2,2,...,2], off = [-1,-1,...,-1].
strang_tri(n) = [vector(n, i, 2), vector(n - 1, i, -1)];

\\ Wilkinson W_{2k+1}: diag = [k,k-1,...,1,0,1,...,k-1,k], off = ones.
wilkinson_w_tri(half) = {
    my(n, d);
    n = 2 * half + 1;
    d = vector(n, i, abs(i - half - 1));
    [d, vector(n - 1, i, 1)];
}

\\ Random integer-valued tridiagonal: diag drawn from {2..6}, off from
\\ {-3..-1, 1..3} (excluding zero so the matrix is non-decoupled). Seeded
\\ via PARI's setrand for reproducibility.
\\
\\ Note: PARI's random(N) returns a value in [0, N). To get integers in
\\ [a, b], compute a + random(b - a + 1).
random_tri(n, seed) = {
    my(diag_v, off_v, raw);
    setrand(seed);
    diag_v = vector(n, i, 2 + random(5));     \\ in [2, 6]
    off_v = vector(n - 1, i,
        raw = 1 + random(3);                  \\ in [1, 3]
        if(random(2) == 0, -raw, raw)         \\ flip sign half the time
    );
    [diag_v, off_v];
}

\\ A tridiagonal where all off-diagonals are equal: diag arithmetic,
\\ off=-1. Closed-form eigenvalues exist for the constant-off case but
\\ we just take PARI's word.
arithmetic_diag_tri(n) = {
    [vector(n, i, i), vector(n - 1, i, -1)];
}

\\ A diagonal-only "tridiagonal" (off-diagonals exactly zero). Tests the
\\ deflation path of the QR algorithm.
diagonal_only_tri(n) = {
    my(diag_v);
    diag_v = vector(n, i, n + 1 - i);   \\ descending: [n, n-1, ..., 1]
    [diag_v, vector(n - 1, i, 0)];
}

\\ Emit one test case as a JSON object. Each case stores diag and
\\ off_diag separately (the form xc-numerics::eigen::tridiag_eigenvalues_hp
\\ expects), plus the reference eigenvalues sorted ascending.
emit_case(name, dpair) = {
    my(diag_v, off_v, M, evals, n, k);
    diag_v = dpair[1];
    off_v = dpair[2];
    n = #diag_v;
    M = build_tridiag(diag_v, off_v);

    evals = polrootsreal(charpoly(M));
    evals = vecsort(evals);
    if(#evals != n,
        error("eigenvalue count ", #evals, " != n=", n, " for case ", name));

    print("    {");
    print("      \"name\": \"", name, "\",");
    print("      \"n\": ", n, ",");

    print("      \"diag\": [");
    for(k = 1, n,
        my(s, sep);
        s = fmt_real(diag_v[k] * 1.0);
        sep = if(k == n, "", ",");
        print("        \"", s, "\"", sep);
    );
    print("      ],");

    print("      \"off_diag\": [");
    for(k = 1, n - 1,
        my(s, sep);
        s = fmt_real(off_v[k] * 1.0);
        sep = if(k == n - 1, "", ",");
        print("        \"", s, "\"", sep);
    );
    print("      ],");

    print("      \"eigenvalues_ascending\": [");
    for(k = 1, n,
        my(s, sep);
        s = fmt_real(evals[k]);
        sep = if(k == n, "", ",");
        print("        \"", s, "\"", sep);
    );
    print("      ]");

    print("    }");
}

emit_case_comma(name, dpair) = {
    emit_case(name, dpair);
    print(",");
}

\\ Main output.
print("{");
print("  \"description\": \"HP tridiagonal-eigensolver reference data generated by PARI/GP via charpoly + polrootsreal at 2000-digit precision\",");
print("  \"realprecision\": ", default(realprecision), ",");
print("  \"cases\": [");

emit_case_comma("strang_n5", strang_tri(5));
emit_case_comma("strang_n10", strang_tri(10));
emit_case_comma("strang_n20", strang_tri(20));
emit_case_comma("wilkinson_w7", wilkinson_w_tri(3));
emit_case_comma("wilkinson_w11", wilkinson_w_tri(5));
emit_case_comma("arithmetic_diag_n8", arithmetic_diag_tri(8));
emit_case_comma("diagonal_only_n6", diagonal_only_tri(6));
emit_case_comma("random_n8_seed1", random_tri(8, 1));
emit_case("random_n12_seed42", random_tri(12, 42));   \\ last, no comma

print("  ]");
print("}");
quit;
